version: '3'

services:
  mongodb:
    container_name: mulocdeepdb2
    image: mongo:4.2.1
    restart: always
    command: mongod --port 65522
    ports:
      - "127.0.0.1:65522:65522"
    volumes:
      - ~/data/db:/data/db
    networks:
      - webapp-network
  web:
    build: .
    container_name: mulocdeepweb2
    image: mulocdeep/mulocdeepweb2
    restart: always
    ports:
      - '127.0.0.1:8083:8083'
    depends_on:
      - mongodb
    networks:
      - webapp-network
networks:
  webapp-network:
    driver: bridge